Fix Java8 error
getServices in a for-each loop was causing compiler error:
"incompatible types: Object cannot be converted to Service"

Bug: 25836540
Change-Id: I711183a76f5aa2cf8ddfaa03516c4622c0b93d4e