path.size() does _not_ include space for the trailing NUL.
We were getting this:

  java.io.FileNotFoundException: /data/system/entropy.dat (No such file or directory

instead of this:

  java.io.FileNotFoundException: /data/system/entropy.dat (No such file or directory)

D'oh!

Change-Id: I8545d157889fefe96934fdc1a01c785e42e84a2d