Revert "Make ZoneInfoTest.testReadSerialized work with CTS"
Fails with vogar:

  libcore.util.ZoneInfoTest#testReadSerialized
    junit.framework.AssertionFailedError: Read ZoneInfo does not match created one: expected libcore.util.ZoneInfo[id="TimeZone for 'testReadSerialized'",mRawOffset=5400000,mEarliestRawOffset=3600000,mUseDst=false,mDstSavings=0,transitions=4] but was libcore.util.ZoneInfo[id="TimeZone for 'test'",mRawOffset=5400000,mEarliestRawOffset=3600000,mUseDst=false,mDstSavings=0,transitions=4]
    	at junit.framework.Assert.assertEquals(Assert.java:100)
    	at libcore.util.ZoneInfoTest.testReadSerialized(ZoneInfoTest.java:403)
  libcore.util.ZoneInfoTest#testReadSerialized FAIL (EXEC_FAILED)

This reverts commit 15de98d71894fc8393df876a6c8f586a39283a3e.

Change-Id: I2de24bcfa8ec8627d63d6c92aa2c708c9a24f9e4