Fix return types so the compiler is happy
The newer compiler is throwing errors of the type:
  error: converting to non-pointer type 'int' from NULL [-Werror=conversion-null]

Change-Id: I5bea50f760a1a9d747b39f9459dab2fbe7fdf7a7