CertPathValidatorException: test new constructor
There is a new constructor that takes a BasicReason as an argument. Test
that it works correctly.

(cherry picked from commit 14a3798a2d6f2f5982e7cb14fc2c562b1d52c2e3)

Bug: 27812109
Change-Id: I957678a774ab91c9fc2854f45f776c23c321960f